name: dispatch
on:
  workflow_dispatch:
    inputs:
      key:
        type: string

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: placeholder
        run: |
          echo "key: ${{ inputs.key }}"
